version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Frontend API
      - "8081:81"  # Backend admin panel
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/cors.conf:/etc/nginx/conf.d/cors.conf
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: loan_app
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U loan_user -d loan_app" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: